# Generated by Django 4.1.7 on 2023-02-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование товара')),
                ('description', models.TextField(max_length=2000, null=True, verbose_name='Описание товара')),
                ('img', models.CharField(max_length=300, verbose_name='Фото')),
                ('category', models.CharField(choices=[('SmartPhone', 'Смартфоны'), ('Tablets', 'Планшеты'), ('PC', 'ПК'), ('NoteBook', 'Ноутбук')], default='Other', max_length=60, verbose_name='Категория')),
                ('remainder', models.IntegerField(verbose_name='Остаток')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Стоимость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
            ],
        ),
    ]
